### Create a new expense
POST http://localhost:3000/expenses
Content-Type: application/json

{
    "description": "Lunch",
    "amount": 15.50,
    "date": "2025-07-18"
}

### Get all expenses
GET http://localhost:3000/expenses

### Get a specific expense by ID
GET http://localhost:3000/expenses/1

### Update an existing expense
PUT http://localhost:3000/expenses/67d08b3a6f52294a2b811f20
Content-Type: application/json

{
    "description": "Lunch with friends",
    "amount": 20.00,
    "date": "2025-07-18"
}

### Delete an expense
DELETE http://localhost:3000/expenses/67d08b3a6f52294a2b811f20